### ISSUE TITLE
Add support for links with a different language

### ISSUE THREAD

**Issue by crackerbad** [roshinc/release-calendar-filter-for-crunchyroll#23]
Currently, the extension is only working on https://www.crunchyroll.com/simulcastcalendar.
When I use Crunchyroll in a language other than English, the extension doesn't work because of the URL change.

Examples:
https://www.crunchyroll.com/es/simulcastcalendar
https://www.crunchyroll.com/pt-br/simulcastcalendar

---

Another suggestion would be to include a filter to remove a specific language like English or German.

**Comment by roshinc** [comment]
Thanks for the issue, 

To get the current filter on the language specific simulcast calendar page, I can probably modify the manifest file. Perhaps maybe I will externalize the strings so I can prep it for multiple languages. I'll work on this hopefully this week.

The second point that you raised, I'm not sure what you mean. If you go the options page you can add more languages to the bar and you show or hide the dubs. Let me know if something is not clear or if I am missing what you are looking for.

**Comment by crackerbad** [comment]
What I meant in the second point is the creation of a filter for excluding a specific language. For example, removing only the English language and keeping the rest.

**Comment by roshinc** [comment]
Sorry for the delay, but version 1.1.4 is out now for both chrome and firefox. This does not have the externalized string but at least it should be functional. 

For you second point, you can do that already:
<img width="1019" alt="image" src="https://github.com/roshinc/release-calendar-filter-for-crunchyroll/assets/2994406/fc74a674-ba83-4720-a13a-e7c1cffd9383">

This configuration will show only dubs that are not English, if that's what you meant

**Comment by roshinc** [comment]
Close this as resolved, feel free to open if issue is present
