### ISSUE TITLE
not working, missing permission?

### ISSUE THREAD

**Issue by Amelie1996** [roshinc/release-calendar-filter-for-crunchyroll#25]
i tried it, not working and the extension tab says that it cant see or change data on the crunchyroll site.

http://puu.sh/JXqif/426bdfb296.jpg

Firefox 118.0.2 (64-Bit) @ win10 22H2, Germany.

would be pretty dope to see it working, i only watch sub, but especially tamil, telugu and hindi dubs are overflowing the calendar. not fun to not see the things i wanna see.

**Comment by roshinc** [comment]
Sorry for the delay this should be fixed with version 1.1.4, it might take a while to be available to you.

<img width="509" alt="image" src="https://github.com/roshinc/release-calendar-filter-for-crunchyroll/assets/2994406/a3a34884-0a24-4f7e-b30b-1b995255a4d0">

**Comment by Amelie1996** [comment]
yess it works now, thank you
