### ISSUE TITLE
Dub regex doesn't match hyphens

### ISSUE THREAD

**Issue by Ebtoulson** [roshinc/release-calendar-filter-for-crunchyroll#4]
https://github.com/roshinc/release-calendar-filter-for-crunchyroll/blob/6fefe306c452c76accfb9b8eff917329df1d8935/ext/src/js/classes/content.js#L4

It looks like CR has added dubs like "English-IN" which won't match the current regex. The dub sounded like English spoken with an Indian accent. Not sure if you'd just want that as another language filter or have it be under "English"

 
![image](https://user-images.githubusercontent.com/1562555/210189261-34aac3bf-7d39-48d3-b75b-ced47cd2836a.png)

**Comment by roshinc** [comment]
Thanks for the letting me know , I think I am going to treat it as a new language

**Comment by roshinc** [comment]
This has been resolved by the latest release, if the extension has not auto updated, you can find it in the extension store. Let me know if you encounter any other issues.
